Models from Proposal
MattKersey/DjangoUnchained pull request #19
Opened 2020-11-09 19:37 UTC by ceguiluzrosas

2020-11-11 11:17 UTC, MattKersey commented
When accessing the /users path, I get an error:
<img width="1262" alt="Screen Shot 2020-11-11 at 6 15 57 AM" src="https://user-images.githubusercontent.com/43304499/98805308-6261ed80-23e5-11eb-8900-afda6ebaa8e0.png">
After doing some digging, I think this is probably tied to line 7 in serializers.py. Changing <code>model = get_user_model</code> to <code>model = get_user_model()</code> fixed the issue for me. Everything else looks great as far as I can tell.

2020-11-11 11:18 UTC, MattKersey requested changes
See comment from conversations.

2020-11-12 03:34 UTC, ceguiluzrosas commented on backend/test_dummy.py
> +    assert 1+1 == 2
Flake8 was giving me an error for this

2020-11-12 03:49 UTC, ceguiluzrosas commented
@MattKersey @jkim10 @yiqiao-liu So I was working to address the change the Matt had mentioned and along the way I realized that something was wrong with the setup of the rest-framework package. I didn't want to hold the project any longer, so I simplified the project to not use the package **for now** so that we can move the team forward in backend-development. I'll try to address the rest_framework issue later. Hope y'all can understand.

2020-11-12 04:34 UTC, yiqiao-liu commented
> @MattKersey @jkim10 @yiqiao-liu So I was working to address the change Matt had mentioned and along the way I realized that something was wrong with the setup of the rest-framework package. I didn't want to hold the project any longer, so I simplified the project to not use the package **for now** so that we can move the team forward in backend-development. I'll try to address the rest_framework issue later. Hope y'all can understand.

Sounds quite reasonable to me!

2020-11-13 14:25 UTC, ceguiluzrosas commented
@MattKersey @yiqiao-liu @jkim10 Should we merge?

2020-11-14 12:36 UTC, MattKersey approved these changes
Looks good to me, seems to be working.

2020-11-14 19:14 UTC, merged